Разметка главной страницы Седона
htmlacademy-htmlcss/1960233-sedona-33 pull request #3
Opened 2022-01-23 10:08 UTC by Samkrite

2022-01-24 06:41 UTC, 4err requested changes
Давай не смешивать задания. Каталог следует делать после принятия первого задания.

Нужно привести форматирование кода к единому виду. Ширина горизонтальных отступов должна быть везде одинаковой: либо 2 либо 4 пробела. Сейчас у тебя отступы разной ширины. 

Одинаковые вещи на разных страницах не повторяю, все актуально и для каталога и главной.

2022-01-24 06:41 UTC, 4err commented on catalog.html
> +        <a class="main-logo">
Логотип должен вести на главную

2022-01-24 06:41 UTC, 4err commented on catalog.html
> +              <a class="navigation-link" href="about.html">Главная</a>
Главная это `index.html`

2022-01-24 06:41 UTC, 4err commented on catalog.html
> +              <a class="navigation-link" href="hotels.html">Гостиницы</a>
Это ж текущая страница и ты назвал ее catalog.html
Нужно избегать создания цикличных ссылок страниц на самих себя. Если элемент является ссылкой, но в какой-то момент он не является ею, потому что, например, ведет на саму себя, мы убираем ему атрибут href. Так браузер и поисковики поймут, что данный элемент, хоть сейчас и не ссылка, но когда-то он ею является.
Нужно исправить здесь и далее.

2022-01-24 06:41 UTC, 4err commented on catalog.html
> +                                <input class="pool-input" type="checkbox" name="Бассейн" checked>
В именах следует использовать латинские слова
Зачем уникальные классы для лейблов и инпутов? они же все одинаковые

2022-01-24 06:41 UTC, 4err commented on catalog.html
> +              <a class="button" href="https://twitter.com/htmlacademy_ru">
button тут не очень подходит, это же не типовая кнопка. Тут нужен отдельный класс для социалок. Ну или доп класс, который переопределяет button

2022-01-24 06:41 UTC, 4err commented on index.html
> +       <img src="" alt="Приветствие"> <!--Не понимаю как разметить векторный текст -->
Картинки достаточно

2022-01-24 06:41 UTC, 4err commented on index.html
> +                <p class="city-text-block-head">НАСТОЯЩИЙ<br>ГОРОДОК</p>
Все тексты пишем по правилам русского языка. Капс добавим с помощью стилизации. 
Старайся не использовать `br`. Почти всегда можно обойтись без них, если не получится, добавим на последнем этапе, а пока убери все br.

2022-01-24 06:41 UTC, 4err commented on index.html
> +          <section class="city">
Обрати внимание, что все причины и преимущества имеют одинаковую структуру и визуально похожи друг на друга. Соответственно у них должна быть одинаковая разметка и классы. Ни к чему дублировать код по разным классам. 

Однако, ты мог заметить, что у некоторых блоков другой цвет шрифта и фона. Для таких случаев используется доп класс, который переопределяет часть свойств. Таким образом нам не нужно дублировать код.

2022-01-24 06:41 UTC, 4err commented on index.html
> +              <button>ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
Это тоже ссылка

2022-01-24 06:41 UTC, 4err commented on index.html
> +              <button>Подписаться</button>
Где-то здесь должна быть форма, чтобы это все работало

2022-01-24 09:17 UTC, Samkrite commented on index.html
> +          <section class="city">
Тут что-то я совсем запутался, попробую упростить и избавиться от лишних классов.

2022-01-25 06:12 UTC, 4err requested changes
Все еще проблема с форматированием:
https://take.ms/pwsQr

Нужно проверить весь код и поправить.
Ссылка на кодгайд, по которому должен писаться код: http://codeguide.academy/html-css.html

В индексе вроде как все хорошо.

2022-01-25 06:12 UTC, 4err commented on index.html
> +      <section class="block-blue">
Но у нас все квадраты одинаковые, кроме фона и текста. Нужно использовать 2 класса: базовый для всех и доп класс для переопределения цвета.

Также давай оформим Список причин списком: `ul`. У нас здесь смысловое перечисление.

2022-01-25 11:07 UTC, Samkrite commented on index.html
> +      <section class="block-blue">
я же могу просто разбить класс? оставить как основной block , а второй уже цвет типо назову case-blue, case-white итд
 class="block  case-white"

2022-01-26 06:10 UTC, merged